---
project_name: modemd

version: 2

release:
  github:
    owner: TheCacophonyProject
    name: modemd
  name_template: '{{.Tag}}'

builds:
  - id: modem-tools
    goos:
      - linux
    goarch:
      - arm64
    goarm:
      - "7"
    main: ./cmd/modem-tools
    ldflags: -s -w -X main.version={{.Version}}
    binary: modem-tools

nfpms:
  - vendor: The Cacophony Project
    homepage: http://cacophony.org.nz/
    maintainer: Cacophony Developers <coredev@cacophony.org.nz>
    description: Controls the USB modems
    license: GPL v3.0
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: _release/modemd.service
        dst: /etc/systemd/system/modemd.service
      - src: _release/org.cacophony.modemd.conf
        dst: /etc/dbus-1/system.d/org.cacophony.modemd.conf
      - src: _release/99-modem-udev.rules
        dst: /etc/udev/rules.d/99-modem-udev.rules
      - src: _release/usbserial.conf
        dst: /etc/modules-load.d/usbserial.conf
      - src: _release/check-gps
        dst: /usr/bin/check-gps
      - src: _release/modem-cli
        dst: /usr/bin/modem-cli
      - src: _release/modemd
        dst: /usr/bin/modemd
      - src: _release/reception-logger
        dst: /usr/bin/reception-logger
    scripts:
      postinstall: "_release/postinstall.sh"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

dist: dist
