---
project_name: modemd

version: 2

release:
  github:
    owner: TheCacophonyProject
    name: modemd
  name_template: '{{.Tag}}'

builds:
  - id: modemd
    goos:
      - linux
    goarch:
      - arm
      - arm64
    goarm:
      - "7"
    main: ./cmd/modemd
    ldflags: -s -w -X main.version={{.Version}}
    binary: modemd

  - id: reception-logger
    goos:
      - linux
    goarch:
      - arm
      - arm64
    goarm:
      - "7"
    main: ./cmd/reception-logger
    ldflags: -s -w -X main.version={{.Version}}
    binary: reception-logger

  - id: modem-cli
    goos:
      - linux
    goarch:
      - arm
      - arm64
    goarm:
      - "7"
    main: ./cmd/modem-cli
    ldflags: -s -w -X main.version={{.Version}}
    binary: modem-cli


nfpms:
  - vendor: The Cacophony Project
    homepage: http://cacophony.org.nz/
    maintainer: Cacophony Developers <coredev@cacophony.org.nz>
    description: Controls the USB modems
    license: GPL v3.0
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: _release/modemd.service
        dst: /etc/systemd/system/modemd.service
      - src: _release/org.cacophony.modemd.conf
        dst: /etc/dbus-1/system.d/org.cacophony.modemd.conf
      - src: _release/99-modem-udev.rules
        dst: /etc/udev/rules.d/99-modem-udev.rules
    scripts:
      postinstall: "_release/postinstall.sh"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

dist: dist
