name: Checks and Goreleaser

on:
  push:
    branches: 
      - '**'  # Run on all branches
    tags:
      - '*'  # Trigger on new tags
  pull_request:
    branches: 
      - '**'  # Trigger on PRs to any branch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Go version from go.mod
        id: go-version
        run: echo "GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')" >> $GITHUB_ENV

      - name: Setting up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Check for Uncommitted Changes
        run: git diff --exit-code || (echo "Please run 'go mod tidy' to clean up the 'go.mod' and 'go.sum' files. Your go version should match the one used with travis." && exit 1)

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Go Tests
        run: go test ./...
      
      - name: GoReleaser Check
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: check

      - name: GoReleaser Release
        uses: goreleaser/goreleaser-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
